name: Test

on:
  workflow_call:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Tests
      shell: pwsh
      run: |
        Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser
        Import-Module Pester
        $result = Invoke-Pester -Path './src/Modules/CretPosh/tests/' -OutputFile reports/test-results.xml -OutputFormat JUnitXml -PassThru
        if ($result.FailedCount -gt 0) {
            throw "$($result.FailedCount) tests failed."
        }

    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        name: "PowerShell tests (${{ matrix.os }})"
        path: reports/test-results-${{ matrix.os }}.xml
        reporter: jest-junit

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: "TestResults (${{ matrix.os }})"
        path: reports/test-results-${{ matrix.os }}.xml